# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  # La liste des filtres
  filter_sets:
    # Nom du Filtre (small)
    small:
      # réglez la qualité de l'image sur 60%
      quality: 50

      # liste des transformations à appliquer sur les "filtres"
      filters:
        thumbnail:
          # Taille de l'image de sortie
          size: [150, 150]

    medium:
      quality: 80
      filters:
        upscale:
          min: [800, 400]
        thumbnail:
          size: [800, 400]
          mode: outbound

    carre:
      quality: 80
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbond

    rectangle:
      quality: 70
      filters:
        thumbnail:
          size: [400, 200]
          mode: outbond

    echelle:
      quality: 80
      filters:
        scale:
          dim: [300, 300]
          mode: outbond

    article:
      quality: 80
      filters:
        upscale:
          min: [400, 200]
        thumbnail:
          size: [400, 200]
          mode: outbound
