#index:
#    path: /
#    controller: App\Controller\DefaultController::index


admin:
    path: /admin
    controller: App\Controller\AdminController::admin


articles:
    path: /articles
    controller: App\Controller\ArticlesController::articles


categories:
    path: /categories
    controller: App\Controller\CategoriesController::categories


livres:
    path: /livres
    controller: App\Controller\LivresController::livres


locations:
    path: /locations
    controller: App\Controller\LocationsController::locations


users:
    path: /users
    controller: App\Controller\UsersController::users


